### ISSUE TITLE
Streamlit down

### ISSUE THREAD

**Issue by apacha** [MarcKletz/OMR-MeasureRecognition#5]
Seems like there is a problem with the streamlit app:

<img width="1170" alt="Screen Shot 2021-04-03 at 11 08 10" src="https://user-images.githubusercontent.com/594497/113474047-a2e20680-946d-11eb-8981-1070dffbd30e.png">

**Comment by MarcKletz** [comment]
Yep, this is a known issue atm.
Will look at this today.
I rebooted the app which temporarily solves this.

**Comment by MarcKletz** [comment]
See Issue #4 for details on why this happens.
